NAME: utility
DESCRIPTION: Provides commonly used functions and macros
TYPE: P
PACKAGES: st mm port
MISC: 
SOURCES: cpu_time.c csystem.c pathsearch.c pipefork.c prtime.c strsav.c texpand.c tmpfile.c
HEADERS: utility.h
OBJECTS: cpu_time.o csystem.o pathsearch.o pipefork.o prtime.o strsav.o texpand.o tmpfile.o
VERBATIMSTART
test:: ${DRIVER}
	@${DRIVER}

VERBATIMEND
TESTNAME: $(NAME)-test
TESTSOURCES: uttest.c
TESTOBJECTS: uttest.o
SYSLIBS: -lm
